version: '3'
services:
  open-gauss:
    image: xy3666/opengauss:latest
    container_name: matrixdl-opengauss
    ports:
      - "5432:5432"
    volumes:
      - ./dbdata:/opt/openGauss/data
    networks:
      - og-network
  grafana:
    image: ghcr.io/sysumatrixdl/grafana:latest
    container_name: matrixdl-grafana
    ports:
      - "3000:3000"
    environment:
      - "GF_SECURITY_ADMIN_PASSWORD=admin"
    depends_on:
      - open-gauss
    networks:
      - og-network
    links:
      - open-gauss
networks:
  og-network:
    driver: bridge
    ipam:
      # 避免和校园网网段(172.12.0.0/16)冲突
      driver: default
      config:
        - subnet: 192.168.114.0/24
          gateway: 192.168.114.254